image: golang:1.21

stages:
  - pre-commit
  - test
  - build


pre-commit:
  stage: pre-commit
  image:
    name: golang:1.21
    entrypoint: [""]
  before_script:
    - apt-get update && apt-get install -y python3 python3-pip
    - pip3 install pre-commit
  script:
    - pre-commit install-hooks
    - pre-commit run --all-files

test:
  stage: test
  script:
    - apt-get install -y xvfb
    - xvfb-run go test ./cmd/main


before_script:
  - go mod download
  - apt-get update -y
   # Courtesy of Fanny Castella for the list of build dependencies
  - apt-get install -y libx11-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libgl1-mesa-dev libxxf86vm-dev

build_linux:
  stage: build
  script:
    - GOOS=linux GOARCH=amd64 go build -o main_linux cmd/main/*.go
  artifacts:
    paths:
      - main_linux

build_windows:
  stage: build
  script:
    - GOOS=windows GOARCH=amd64 go build -o main_windows.exe cmd/main/*.go
  artifacts:
    paths:
      - main_windows.exe