stages:
  - build

build_mac:
  stage: build
  image: golang:1.21
  script:
    - GOOS=darwin GOARCH=amd64 go build -o main_mac cmd/main/*.go
  artifacts:
    paths:
      - main_mac

build_linux:
  stage: build
  image: golang:1.21
  script:
    - GOOS=linux GOARCH=amd64 go build -o main_linux cmd/main/*.go
  artifacts:
    paths:
      - main_linux

build_windows:
  stage: build
  image: golang:1.21
  script:
    - GOOS=windows GOARCH=amd64 go build -o main_windows.exe cmd/main/*.go
  artifacts:
    paths:
      - main_windows.exe