stages:
  - build



before_script:
  - go mod download
  - apt-get update -y
  - apt-get install -y libx11-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libgl1-mesa-dev libxxf86vm-dev

build_mac:
  stage: build
  image: golang:alpine
  script:
    - GOOS=darwin GOARCH=amd64 go build -o main_mac cmd/main/*.go
  artifacts:
    paths:
      - main_mac

build_linux:
  stage: build
  image: golang:alpine
  script:
    - apk add --update alpine-sdk libx11-dev tiff-dev
    - GOOS=linux GOARCH=amd64 go build -o main_linux cmd/main/*.go
  artifacts:
    paths:
      - main_linux

build_windows:
  stage: build
  image: golang:alpine
  script:
    - GOOS=windows GOARCH=amd64 go build -o main_windows.exe cmd/main/*.go
  artifacts:
    paths:
      - main_windows.exe