name: Go CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libx11-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libgl1-mesa-dev libxxf86vm-dev

      - name: Download Go modules
        run: go mod download

      - name: Run tests
        run: xvfb-run go test ./cmd/main

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libgl1-mesa-dev libxxf86vm-dev

      - name: Download Go modules
        run: go mod download

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o main_linux cmd/main/*.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o main_windows.exe cmd/main/*.go

      - name: Build WebAssembly
        run: GOOS=js GOARCH=wasm go build -o main.wasm cmd/main/*.go

      - name: Copy wasm_exec.js
        run: cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .

      - name: Copy existing index.html
        run: cp wasm/index.html .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            main_linux
            main_windows.exe
            main.wasm
            wasm_exec.js
            index.html

  deploy-gh-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: builds

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
